##########################################################################
#
# - Role pre-req checks
# - Will fail if not complainat options found
# 
#
# 
# Alexey Mikhaylov
# NetApp Deutschland GmbH
# Professional Services 2024
##########################################################################
---
- name: Validate all input params are provided
  ansible.builtin.assert:
    that:
      - input_env is defined
      - input_size is defined
      - input_snaplock is defined
      - input_clientmatch is defined
      - input_proc is defined
    msg: "Input data isn't correct. Cannot continue: input_env, input_size, input_snaplock, input_clientmatch, input_proc are mandatory"

- name: Validate inventory
  ansible.builtin.assert:
    that:
      - (inventory_svms_mcc is defined) and (inventory_svms_mcc.keys() | length > 0)
      - (inventory_svms_vault is defined) and (inventory_svms_vault.keys() | length > 0)
    msg: "Inventory data isn't correct. Cannot continue: inventory_svms_mcc, inventory_svms_vault are mandatory"

- name: Validate input environment control parameters
  ansible.builtin.fail:
    msg:
      - "Input data isn't correct. Cannot continue: input_env not given or not in the list. input value: {{ input_env | default('') }}"
  when:
    - ((input_env is not defined) or (input_env | upper not in storage_env)) and (input_env[:1] | upper not in ['F'])

- name: Validate input control parameters
  ansible.builtin.fail:
    msg:
      - "Input data isn't correct. Cannot continue: input_dryrun not in ['true', 'false', 'yes', 'no']. input value: {{ input_dryrun }}"
  when:
    - input_dryrun | lower is not in ['true', 'false', 'yes', 'no']
    
- name: Validate input size parameters
  ansible.builtin.fail:
    msg:
      - "Input data isn't correct. Cannot continue: input_size not given or incorrect size. Input value: {{ input_size | default('') }}"
  when:
    - (input_size is not defined) or (input_size | int not in volume_sizes)

- name: Validate input Export policy clientmatch parameters
  ansible.builtin.fail:
    msg:
      - "Input data isn't correct. Cannot continue: input_clientmatch not given or incorrect value. Input value: {{ input_clientmatch | default('') }}"
  when:
    - input_clientmatch is not ansible.utils.ipv4

- name: Validate input procedure parameters
  ansible.builtin.fail:
    msg:
      - "Input data isn't correct. Cannot continue: input_proc not given or incorrect length (5). Input value: {{ input_proc | default('') }}"
  when:
    - input_proc | length != 5

- name: Validate logging parameters
  ansible.builtin.assert:
    msg:
      - "Log folder is not set! qlogdir: {{ qlogdir | default('') }}"
    that:
      - qlogdir is defined

#####################
# Snaplock related checks
#####################
- name: Validate input aggregate Snaplock parameters
  ansible.builtin.fail:
    msg:
      - "Input data isn't correct. Cannot continue: input_snaplock not given or incorrect value. Input value: {{ input_snaplock | default('') }}"
  when:
    - (input_snaplock is not defined) or (input_snaplock is not boolean)
    - input_snaplock is not boolean


- name: Validate Snaplock input parameters
  ansible.builtin.assert:
    that:
      - input_sl_params is defined
      - input_sl_params| type_debug == 'dict'
      - input_sl_params.autocommit_period | netapp_ps.ontap.is_duration
      - input_sl_params.retention is defined
      - input_sl_params.retention | type_debug == 'dict'
      - input_sl_params.retention.minimum is defined
      - input_sl_params.retention.maximum is defined
      - input_sl_params.retention.default is defined
      - input_sl_params.retention.minimum | netapp_ps.ontap.is_duration
      - input_sl_params.retention.maximum | netapp_ps.ontap.is_duration
      - input_sl_params.retention.default | netapp_ps.ontap.is_duration
    msg:
      - "Input Snaplock data isn't correct. Cannot continue: input_sl_params not given or incorrect value. Input value: {{ input_sl_params | default('') }}"
  when:
    - input_snaplock is defined
    - input_snaplock | bool

...