##########################################################################
#
# - input valiables preparation tasks
# 
#
# 
# Alexey Mikhaylov
# NetApp Deutschland GmbH
# Professional Services 2024
##########################################################################
---
# shorten name for FUS environment
# NOTE: this is a special case for FUS environment
# *** DISABLED ***
#
# it is now executed in bypass mode
- name: Prepare special case environment FUS-n
  ansible.builtin.set_fact:
    input_env_fact: "{{ input_env | netapp_ps.bper.shorten_fus }}"

...